name: "🔒 Studio PUPSI: DevSecOps Quality & Security Scan"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-validate:
    name: "1. Validate & Lint Infrastructure"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup Terraform Environment
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.0

    - name: Check Code Formatting
      run: terraform fmt -check -recursive iac/

    - name: Validate Terraform Syntax
      run: |
        cd iac/
        terraform init -backend=false
        terraform validate

  security-scan:
    name: "2. DevSecOps Vulnerability Scan"
    needs: terraform-validate  # Läuft erst, wenn die Validierung fehlerfrei war
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@v0.35.0   # Sichere, geprüfte Release-Version verwenden
      with:
        scan-type: 'fs'                        # Scannt das gesamte Dateisystem (Code & Configs)
        scanners: 'vuln,secret,config'         # Prüft auf Schwachstellen, Passwörter und Fehlkonfigurationen
        severity: 'CRITICAL,HIGH'              # Meldet nur kritische und schwere Alarme
        hide-progress: true
